name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install libudev-sys v0.1.4
      run: sudo apt-get install -y libudev-sys
    - name: install libxml2-utils
      run: sudo apt-get install -y libxml2-utils
    - name: Build
      run: cargo build --verbose
 
